services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: todo_api
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "53306:3306"
    networks:
      - todo_network

  # PHP-FPM контейнер
  app:
    build: .
    container_name: todo_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - todo_network

  nginx:
    image: nginx:alpine
    container_name: todo_nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge
